### ISSUE TITLE
Explicit dependency on mod_glossary

### ISSUE THREAD

**Issue by mudrd8mz** [dthies/moodle-qformat_glossary#1]
This plugin depends on mod_glossary as it uses its libraries. Even if the Glossary is a standard activity module, it is preferred to explicitly declare the dependency in the version.php file (https://docs.moodle.org/dev/version.php) to prevent unexpected behaviour if the Glossary is uninstalled, for example.

**Comment by dthies** [comment]
Thank you, very much David. Also added dependence for qformat_xml
